[GOD-2285] Camera: clearer UI about microphone injection
Genymobile/genymotion-device-web-player pull request #20
Opened 2023-01-16 13:36 UTC by guillaume-roche

## Description

Some customers do want to use microphone injection. It happens that our camera feature injects both webcam and microphone into the virtual device, but the UI is only about camera.

- Update icon to show that it enables both camera and microphone.
- Update tooltip accordingly.
- Update README

![image](https://user-images.githubusercontent.com/6976869/212690778-dbe49978-c573-41f3-b539-a7ecf07d0d6d.png)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I've read & comply with the [contributing guidelines](https://github.com/Genymobile/genymotion-device-web-player/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] I have made corresponding changes to the documentation (README.md).
- [x] I've checked my modifications for any breaking changes.

2023-01-16 13:49 UTC, JulienBolard requested changes
This is not available on SaaS. We need to keep the old behavior / look n feel for it

2023-01-16 16:01 UTC, guillaume-roche commented
> This is not available on SaaS. We need to keep the old behavior / look n feel for it

Ah right, I missed the `microphone`. Added a commit to take it into account. Also tested with both values for this option.

2023-01-17 13:15 UTC, cmajed approved these changes

2023-01-17 13:44 UTC, agavignet approved these changes

2023-01-18 14:10 UTC, JulienBolard approved these changes

2023-01-18 15:59 UTC, merged