System 2449/fix gamepad
Genymobile/genymotion-device-web-player pull request #73
Opened 2024-04-05 14:17 UTC by cmajed

## Description
Rework Gamepad and Gamepad Management to fix:
        - handle gamepad pugged/unplugged
        - catch and handle confirmation
        - send correct vinput gamepad redis message
        - Handle axis changes
        - Rework catch and dispatch event to dispatch it only when axes changed
        - Add vendor id and product id to the plugg in command
        
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I've read & comply with the [contributing guidelines](https://github.com/Genymobile/genymotion-device-web-player/blob/main/CONTRIBUTING.md)
- [ ] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] I have made corresponding changes to the documentation (README.md).
- [ ] I've checked my modifications for any breaking changes.

2024-04-08 07:22 UTC, jparez approved these changes
LGTM

2024-04-08 09:10 UTC, pgivel commented
I think the first commit should not be in this PR ? Or maybe this PR should not target `main` ?

2024-04-08 09:20 UTC, cmajed commented
yes it cames from this PR
https://github.com/Genymobile/genymotion-device-web-player/pull/72
I could target it instead!

2024-04-08 09:24 UTC, pgivel requested changes

2024-04-08 09:24 UTC, pgivel commented on src/plugins/GamepadManager.js
>      onGamepadConnected(event) {
maybe rename this to `onGamepadConnectionEvent`?

2024-04-08 09:24 UTC, pgivel commented on src/plugins/GamepadManager.js
> +        return undefined;
I think `return null` should be fine

2024-04-08 09:24 UTC, pgivel commented on src/plugins/GamepadManager.js
>      listenForInputs(localIndex, remoteIndex) {
I guess you could rename these to `hostIndex` and `guestIndex` for clarity & consistency with the desktop app

2024-04-08 09:24 UTC, pgivel commented on src/plugins/GamepadManager.js
> +        const gamepad = this.getRawGamepad(remoteIndex);
it's very weird to me that we use the remoteIndex here?  I think in the raw gamepads the `index` is the local one?

2024-04-08 12:45 UTC, pgivel requested changes

2024-04-08 12:45 UTC, pgivel commented on src/plugins/GamepadManager.js
>      onGamepadDisonnected(event) {
oops I left a typo here
```suggestion
    onGamepadDisconnected(event) {
```

2024-04-08 12:45 UTC, pgivel commented on src/plugins/GamepadManager.js
> +        if (event.type === 'gamepadconnected') {
same here, I don't think this check is needed?

2024-04-12 07:52 UTC, pgivel approved these changes

2024-04-12 08:07 UTC, merged