Dev/api manager
Genymobile/genymotion-device-web-player pull request #78
Opened 2024-06-11 11:23 UTC by jparez

## Description

adding an apiManager to expose player API. 

This is a breaking change since we setupRender return the API, not the deviceRenderFactory object

Fixes #<issue>

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I've read & comply with the [contributing guidelines](https://github.com/Genymobile/genymotion-device-web-player/blob/main/CONTRIBUTING.md)
- [ ] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [ ] I have made corresponding changes to the documentation (README.md).
- [ ] I've checked my modifications for any breaking changes.

2024-06-11 14:28 UTC, pgivel requested changes
code looks great, some small suggestions on the README

2024-06-11 15:25 UTC, pgivel approved these changes

2024-06-12 08:33 UTC, caarmen commented on src/APIManager.js
> +    getExposedApiFunctions() {
Can we have JSDoc indicating the types of objects which are returned, in the functions which return something?

2024-06-12 08:33 UTC, caarmen commented on src/APIManager.js
> +            () => this.listRegisteredFunctions(),
Could we have the same name in both places? Either `getRegisteredFunctions` or `listRegisteredFunctions`, but not both at the same time?

2024-06-12 08:33 UTC, caarmen commented on README.md
> +plugin options and websocket communication can be handle trought the API object returned by setupRenderer function.
```suggestion
Plugin options and websocket communication can be handled through the API object returned by the `setupRenderer` function.
```

2024-06-12 08:33 UTC, caarmen commented on README.md
> +which return the list of available functions with an optionnal description
```suggestion
which returns the list of available functions with an optional description
```

2024-06-12 08:33 UTC, caarmen commented on README.md
> +which disconnect player from VM and cleanup memory listener
```suggestion
which disconnects the player from the VM and cleanups the memory listener
```

2024-06-12 08:33 UTC, caarmen commented on README.md
> +used to listen messages emit from VM such as 'fingerprint', 'gps', 'BATTERY_LEVEL'
```suggestion
used to listen to messages emitted from the VM such as 'fingerprint', 'gps', 'BATTERY_LEVEL'
```

2024-06-12 08:33 UTC, caarmen commented on README.md
> +used to send message to VM.
```suggestion
used to send messages to the VM.
```

2024-06-12 12:17 UTC, caarmen approved these changes
I don't have the full context to review beyond a surface level.

Just checked the documentation mostly, which LGTM :)

2024-06-12 12:39 UTC, merged