[PLAYER-19] keybinding (post refacto dialog)
Genymobile/genymotion-device-web-player pull request #82
Opened 2024-06-14 12:12 UTC by jparez

## Description

Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context (a screenshot is appreciated).

Fixes #<issue>

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

-   [ ] I've read & comply with the [contributing guidelines](https://github.com/Genymobile/genymotion-device-web-player/blob/main/CONTRIBUTING.md)
-   [ ] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
-   [ ] I have made corresponding changes to the documentation (README.md).
-   [ ] I've checked my modifications for any breaking changes.

2024-06-26 08:51 UTC, jparez commented on src/APIManager.js
Added a category for API manager exposed fn => window.player.media.mute()

2024-06-26 08:53 UTC, jparez commented on src/DeviceRenderer.js
> -
Click handler handle has been move to overlayplugin class (decoupling)

2024-06-26 08:53 UTC, jparez commented on src/DeviceRenderer.js
decoupling see above

2024-06-26 08:54 UTC, jparez commented on src/plugins/FingerPrint.js
> -        if (this.instance.store.getState().isWebRTCConnectionReady) {
getState was unecessary for a little store,

2024-06-26 08:55 UTC, jparez commented on src/plugins/Fullscreen.js
> +        this.instance.apiManager.registerFunction({
Requested from socis

2024-06-26 08:55 UTC, jparez commented on src/plugins/KeyboardEvents.js
> +            if (isKeyboardEventsEnabled) {
little refact to decoupling keyboard handle events of deviceRenderer js

2024-06-26 08:56 UTC, jparez commented on src/plugins/MediaManager.js
> +            name: 'mute',
added category

2024-06-26 08:56 UTC, jparez commented on src/plugins/MouseEvents.js
> +        this.removeMouseUpListener = () => {};
removeMouseUplistener will never be undefined

2024-06-26 08:57 UTC, jparez commented on src/plugins/util/OverlayPlugin.js
> +        if (!OverlayPlugin.hasBeenCalled) {
it's a kind of static method for a Class, this way we attach the listener only once

2024-07-10 08:53 UTC, pgivel requested changes
This is looking great. Most of my comments are about documentation, since this feature is a bit complicated to understand, I think it benefits from being as documented as possible.

I didn't much review the debug stuff (grid and trace), since I trust you that it works well enough.

2024-07-10 08:53 UTC, pgivel commented on src/plugins/KeyboardMapping.js
> +        // register api function
maybe, for code clarity, extract the api functions registering to a function?

2024-07-10 08:53 UTC, pgivel commented on src/plugins/KeyboardMapping.js
> +            description: 'Submit a config for mapping keys',
maybe explain that the function expects a stringified json as arg? By the way, why not letting the user do the json parsing, that way we could directly take a js object as arg?

2024-07-10 08:53 UTC, pgivel commented on src/plugins/KeyboardMapping.js
> +    setupMappedKeysConfig() {
maybe add a doc comment explaining that this simply flattens the structure, and what `mappedKeysConfig` and `workingMappedKeysConfig` are?

2024-07-10 08:53 UTC, pgivel commented on src/plugins/KeyboardMapping.js
> +        // if another key is always pressed then initial coord must be from lastpoint
do you mean "already pressed"?

2024-07-10 09:16 UTC, jparez commented on src/plugins/KeyboardMapping.js
> +            this.instance.store.dispatch({type: 'MOUSE_EVENTS_ENABLED', payload: !this.state.isPaused});
IsActive is the boolean that indicate if player is active or disabled. 
Now, think about open a window plugin (like clipboard or gps) you need tu remove event listener from keymapping plugin, but when you close the widget plugin you want to reactivate the plugin.

Now the trick : store trigger all subscribe fn and when a plugin is close we need to rebind keymapping only if the previsous state was active, this is why we have isActive (change when click on icon of the toolbar) et isPaused (isActive but currently not catch keyboardevent event)

2024-07-10 13:44 UTC, jparez commented on src/APIManager.js
>              },
lambda and bind work same here, it's a personal preference. 
For the shorter syntax we need to configure eslint because by default it is not permit

2024-07-10 13:45 UTC, jparez commented on src/scss/components/_toolbar.scss
> +            &.keymapping-paused {
paused and disabled are two different state

2024-07-10 13:51 UTC, jparez commented on src/store/index.js
> +            break;
this error can only happen during the developpement phase. We can add a trace to help with debugging but this trace should never be displayed in production mode

2024-07-10 14:03 UTC, pgivel commented on src/scss/components/_toolbar.scss
> +            &.keymapping-paused {
yep, I understood that later, but the css class name and the asset name are not consistent.

2024-07-11 11:56 UTC, pgivel approved these changes

2024-07-18 13:37 UTC, pgivel approved these changes

2024-07-25 12:28 UTC, merged